### ISSUE TITLE
login key

### ISSUE THREAD

**Issue by Huguitis** [kragleh/pterotunnel#1]
Hello, when I put the login key (pterodactyl enduser api key) it does not log in

**Comment by kragleh** [comment]
You will have to modify the pterodactyl panel API to send Access-Control-Allow-Origin header including your pterotunnel panel domain else your going to get an error similar to the one shown below, or you can bypass this by disabling CORS by using an extension in your browser which is not recommended. Either way this repo is just a concept of an application I might need in the future and its not production ready so keep that im mind.
![image](https://user-images.githubusercontent.com/108424057/225619890-ce9a4dda-54e1-4a78-8c8a-994086318e42.jpg)

**Comment by Huguitis** [comment]
Amazing, thanks!
